### ISSUE TITLE
Fix 'fulfils' to 'fulfills' on p.39 of PA

### ISSUE THREAD

**Issue by martinmoene** [JonJagger/two-day-courses#7]
On p.39 of Python Advanced, in _A dummy object fulfils a dependency_:

`s/fulfils/fulfills/`

**Comment by RichardBrookfield** [comment]
Both are right depending on audience: fulfil=UK and fulfill=US.

**Comment by martinmoene** [comment]
Ah, thanks. 

From [Grammarist](http://grammarist.com/spelling/fulfil-fulfill/):

>this [ngram](http://books.google.com/ngrams/graph?content=fulfil%2Cfulfill&year_start=1800&year_end=2000&corpus=5&smoothing=3), which graphs the words’ use in American books from the same period, suggests that the transition from fulfil to fulfill  occurred in the first half of the 20th century
